### ISSUE TITLE
MacOS 12.6.3 error for "bundle install --path=vendor/bundle && bundle exec pod install "

### ISSUE THREAD

**Issue by renjwjx** [Clipy/Clipy#523]
jinren@Jinrens-Mac-Mini-2 Clipy-develop % bundle install --path=vendor/bundle && bundle exec pod instal
Fetching gem metadata from https://rubygems.org/........
Using rake 13.0.1
Using CFPropertyList 3.0.2
Using public_suffix 4.0.6
Using addressable 2.7.0
Using atomos 0.1.3
Using aws-eventstream 1.1.0
Using aws-partitions 1.385.0
Using aws-sigv4 1.2.2
Using jmespath 1.4.0
Using aws-sdk-core 3.109.1
Using aws-sdk-kms 1.39.0
Using aws-sdk-s3 1.83.1
Using babosa 1.0.4
Using bundler 2.1.4
Using claide 1.0.3
Using colored2 3.1.2
Using cork 0.3.0
Using nap 1.1.0
Using open4 1.3.4
Using claide-plugins 0.9.2
Using colored 1.2
Using highline 1.7.10
Using commander-fastlane 4.4.6
Using multipart-post 2.0.0
Using ruby2_keywords 0.0.2
Using faraday 1.1.0
Using faraday-http-cache 2.2.0
Using rchardet 1.8.0
Using git 1.7.0
Using rexml 3.2.4
Using kramdown 2.3.0
Using kramdown-parser-gfm 1.1.0
Using no_proxy_fix 0.1.2
Using sawyer 0.8.2
Using octokit 4.19.0
Using unicode-display_width 1.7.0
Using terminal-table 1.8.0
Using danger 8.1.0
Using thor 0.20.3
Using danger-swiftlint 0.24.4
Using declarative 0.0.20
Using declarative-option 0.1.0
Fetching digest-crc 0.6.1
Installing digest-crc 0.6.1 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/jinren/Documents/Github/Clipy-develop/vendor/bundle/ruby/2.6.0/gems/digest-crc-0.6.1/ext/digest
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -rrubygems
/Users/jinren/Documents/Github/Clipy-develop/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/exe/rake
RUBYARCHDIR\=/Users/jinren/Documents/Github/Clipy-develop/vendor/bundle/ruby/2.6.0/extensions/universal-darwin-21/2.6.0/digest-crc-0.6.1
RUBYLIBDIR\=/Users/jinren/Documents/Github/Clipy-develop/vendor/bundle/ruby/2.6.0/extensions/universal-darwin-21/2.6.0/digest-crc-0.6.1
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -S extconf.rb
checking for stdint.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/$(RUBY_BASE_NAME)
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file.
(RuntimeError)
You have to install development tools first.
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:585:in `block in try_compile'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:534:in `with_werror'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:585:in `try_compile'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:1109:in `block in have_header'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:959:in `block in checking_for'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:361:in `block (2 levels) in postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:331:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:361:in `block in postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:331:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:357:in `postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:958:in `checking_for'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:1108:in `have_header'
	from extconf.rb:3:in `<main>'
rake aborted!
Command failed with status (1): [/System/Library/Frameworks/Ruby.framework/...]
/Users/jinren/Documents/Github/Clipy-develop/vendor/bundle/ruby/2.6.0/gems/digest-crc-0.6.1/ext/digest/Rakefile:32:in `block (3 levels) in <top (required)>'
/Users/jinren/Documents/Github/Clipy-develop/vendor/bundle/ruby/2.6.0/gems/digest-crc-0.6.1/ext/digest/Rakefile:31:in `chdir'
/Users/jinren/Documents/Github/Clipy-develop/vendor/bundle/ruby/2.6.0/gems/digest-crc-0.6.1/ext/digest/Rakefile:31:in `block (2 levels) in <top (required)>'
/Users/jinren/Documents/Github/Clipy-develop/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<main>'
Tasks: TOP => default => crc16_genibus/crc16_genibus_ext.bundle => crc16_genibus/Makefile
(See full trace by running task with --trace)

rake failed, exit code 1

Gem files will remain installed in /Users/jinren/Documents/Github/Clipy-develop/vendor/bundle/ruby/2.6.0/gems/digest-crc-0.6.1 for inspection.
Results logged to /Users/jinren/Documents/Github/Clipy-develop/vendor/bundle/ruby/2.6.0/extensions/universal-darwin-21/2.6.0/digest-crc-0.6.1/gem_make.out

An error occurred while installing digest-crc (0.6.1), and Bundler cannot continue.
Make sure that `gem install digest-crc -v '0.6.1' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  fastlane was resolved to 2.165.0, which depends on
    google-cloud-storage was resolved to 1.29.1, which depends on
      digest-crc

**Comment by renjwjx** [comment]
jinren@Jinrens-Mac-Mini-2 Clipy-develop % **sudo gem install digest-crc -v '0.6.1' --source 'https://rubygems.org/'**
Password:
Fetching digest-crc-0.6.1.gem
Fetching rake-13.0.6.gem
Successfully installed rake-13.0.6
Building native extensions. This could take a while...
ERROR:  Error installing digest-crc:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.6.0/gems/digest-crc-0.6.1/ext/digest
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -rrubygems /Library/Ruby/Gems/2.6.0/gems/rake-13.0.6/exe/rake RUBYARCHDIR\=/Library/Ruby/Gems/2.6.0/extensions/universal-darwin-21/2.6.0/digest-crc-0.6.1 RUBYLIBDIR\=/Library/Ruby/Gems/2.6.0/extensions/universal-darwin-21/2.6.0/digest-crc-0.6.1
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -S extconf.rb
checking for stdint.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/$(RUBY_BASE_NAME)
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:585:in `block in try_compile'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:534:in `with_werror'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:585:in `try_compile'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:1109:in `block in have_header'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:959:in `block in checking_for'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:361:in `block (2 levels) in postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:331:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:361:in `block in postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:331:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:357:in `postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:958:in `checking_for'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:1108:in `have_header'
	from extconf.rb:3:in `<main>'
rake aborted!
Command failed with status (1): [/System/Library/Frameworks/Ruby.framework/...]
/Library/Ruby/Gems/2.6.0/gems/digest-crc-0.6.1/ext/digest/Rakefile:32:in `block (3 levels) in <top (required)>'
/Library/Ruby/Gems/2.6.0/gems/digest-crc-0.6.1/ext/digest/Rakefile:31:in `chdir'
/Library/Ruby/Gems/2.6.0/gems/digest-crc-0.6.1/ext/digest/Rakefile:31:in `block (2 levels) in <top (required)>'
/Library/Ruby/Gems/2.6.0/gems/rake-13.0.6/exe/rake:27:in `<main>'
Tasks: TOP => default => crc16_genibus/crc16_genibus_ext.bundle => crc16_genibus/Makefile
(See full trace by running task with --trace)

rake failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.6.0/gems/digest-crc-0.6.1 for inspection.
Results logged to /Library/Ruby/Gems/2.6.0/extensions/universal-darwin-21/2.6.0/digest-crc-0.6.1/gem_make.out

**Comment by Econa77** [comment]
Closing this issue because the build / dependency setup error should be resolved by #591.

For context about the project restart and issue cleanup policy, please see: #590

Thank you for the report, and I am sorry it took such a long time to address this.

If the same error still reproduces after the changes from #591, please feel free to open a new issue with updated details.
